import type { DimensionDescriptor, PersonalityProfile, Question } from "@/domain/vcti/types";

export const dimensions: DimensionDescriptor[] = [
  {
    id: "MA",
    name: "掌控倾向",
    subtitle: "Manual vs AI Reliance",
    leftLetter: "M",
    rightLetter: "A",
    leftLabel: "手工匠心",
    rightLabel: "AI 依赖",
    leftFullName: "Manual",
    rightFullName: "AI Reliance",
    summary: "衡量你是亲手掌控实现，还是更愿意把生成工作交给 AI。",
    detailTitle: "掌控倾向说明",
    detailBody:
      "M 侧偏向亲自构思与手写代码，把编写过程视为思考的一部分；A 侧偏向通过 Prompt 和生成式工具放大产能，把 AI 当成主要执行层。",
  },
  {
    id: "DV",
    name: "认知深度",
    subtitle: "Deep Logic vs Vibe Logic",
    leftLetter: "D",
    rightLetter: "V",
    leftLabel: "深层逻辑",
    rightLabel: "氛围感知",
    leftFullName: "Deep Logic",
    rightFullName: "Vibe Logic",
    summary: "衡量你是否需要理解底层原理，还是更看重结果是否工作。",
    detailTitle: "认知深度说明",
    detailBody:
      "D 侧在意原理、复杂度、文档和源码，理解机制才能安心；V 侧更相信直觉和反馈循环，只要结果成立，内部细节可以先黑盒化。",
  },
  {
    id: "RJ",
    name: "验证态度",
    subtitle: "Rigorous Audit vs Just Vibe It",
    leftLetter: "R",
    rightLetter: "J",
    leftLabel: "严谨审计",
    rightLabel: "随缘运行",
    leftFullName: "Rigorous Audit",
    rightFullName: "Just Vibe It",
    summary: "衡量你对测试、审计和上线风险的容忍度。",
    detailTitle: "验证态度说明",
    detailBody:
      "R 侧会主动补测试、审阅生成代码、控制提交质量；J 侧更偏向先跑通再说，把真实环境反馈当成主要验证手段。",
  },
  {
    id: "CP",
    name: "驱动目标",
    subtitle: "Code Driven vs Product Driven",
    leftLetter: "C",
    rightLetter: "P",
    leftLabel: "代码导向",
    rightLabel: "产品导向",
    leftFullName: "Code Driven",
    rightFullName: "Product Driven",
    summary: "衡量你更在意代码质量本身，还是更在意交付目标。",
    detailTitle: "驱动目标说明",
    detailBody:
      "C 侧更在意结构、可维护性、命名与长期工程质量；P 侧把代码视为交付工具，只要功能足够快地到达用户，局部粗糙可以接受。",
  },
];

export const questions: Question[] = [
  {
    id: "MA1",
    prompt: "在实现核心业务逻辑时，我倾向于自己构思并手写，而非让 AI 生成。",
    dimension: "MA",
    category: "core",
    input: "likert",
    direction: "left",
  },
  {
    id: "MA2",
    prompt: "AI 生成的代码量越多，我审计时的不安感越强。",
    dimension: "MA",
    category: "core",
    input: "likert",
    direction: "left",
  },
  {
    id: "MA3",
    prompt: "让 AI 直接生成整个功能模块是目前最极致的开发效率。",
    dimension: "MA",
    category: "core",
    input: "likert",
    direction: "right",
  },
  {
    id: "MA4",
    prompt: "我会花时间微调 Prompt，直到 AI 给出令我满意的答案，而不是自己修改代码。",
    dimension: "MA",
    category: "core",
    input: "likert",
    direction: "right",
  },
  {
    id: "MA5",
    prompt: "我觉得“手写代码”是程序员的尊严，是思考的唯一方式。",
    dimension: "MA",
    category: "core",
    input: "likert",
    direction: "left",
  },
  {
    id: "DV1",
    prompt: "我必须理解 AI 方案在底层是如何运作的，否则不放心。",
    dimension: "DV",
    category: "core",
    input: "likert",
    direction: "left",
  },
  {
    id: "DV2",
    prompt: "面对新库，我习惯先阅读官方文档而非直接询问 AI。",
    dimension: "DV",
    category: "core",
    input: "likert",
    direction: "left",
  },
  {
    id: "DV3",
    prompt: "只要结果正确，内部实现机制对我而言可以是一个黑盒。",
    dimension: "DV",
    category: "core",
    input: "likert",
    direction: "right",
  },
  {
    id: "DV4",
    prompt: "我经常凭直觉修改代码，然后运行看看结果，而不是严谨推理。",
    dimension: "DV",
    category: "core",
    input: "likert",
    direction: "right",
  },
  {
    id: "DV5",
    prompt: "我享受深入源码、理解设计原理的过程，即使这很耗时。",
    dimension: "DV",
    category: "core",
    input: "likert",
    direction: "left",
  },
  {
    id: "RJ1",
    prompt: "“本地跑通了”绝对不是代码可以提交到生产环境的充分条件。",
    dimension: "RJ",
    category: "core",
    input: "likert",
    direction: "left",
  },
  {
    id: "RJ2",
    prompt: "我愿意花比写代码更多的时间去编写测试用例以确保 AI 未出错。",
    dimension: "RJ",
    category: "core",
    input: "likert",
    direction: "left",
  },
  {
    id: "RJ3",
    prompt: "只要运行一次没报错且功能正常，我就倾向于直接上线。",
    dimension: "RJ",
    category: "core",
    input: "likert",
    direction: "right",
  },
  {
    id: "RJ4",
    prompt: "我的 Commit Message 通常是 “update”“fix”“vibe check” 这类。",
    dimension: "RJ",
    category: "core",
    input: "likert",
    direction: "right",
  },
  {
    id: "RJ5",
    prompt: "没有通过单元测试的代码，我绝对不会提交。",
    dimension: "RJ",
    category: "core",
    input: "likert",
    direction: "left",
  },
  {
    id: "CP1",
    prompt: "我无法忍受功能正确但结构臃肿的代码，即使已上线也会重构。",
    dimension: "CP",
    category: "core",
    input: "likert",
    direction: "left",
  },
  {
    id: "CP2",
    prompt: "代码的优雅与可维护性，与功能的实现同等重要。",
    dimension: "CP",
    category: "core",
    input: "likert",
    direction: "left",
  },
  {
    id: "CP3",
    prompt: "代码仅是工具，只要能快速交付且不影响用户，丑一点没关系。",
    dimension: "CP",
    category: "core",
    input: "likert",
    direction: "right",
  },
  {
    id: "CP4",
    prompt: "我经常为了赶进度而写出“能跑就行”的代码，过后也不打算重构。",
    dimension: "CP",
    category: "core",
    input: "likert",
    direction: "right",
  },
  {
    id: "CP5",
    prompt: "我会花时间优化代码的可读性和命名规范，即使没人会看。",
    dimension: "CP",
    category: "core",
    input: "likert",
    direction: "left",
  },
  {
    id: "SCN1",
    prompt: "打开空白编辑器，你的第一反应是？",
    category: "scenario",
    input: "choice",
    choices: [
      { value: -3, label: "打开键盘，开始写", hint: "先自己敲" },
      { value: 0, label: "想一下架构", hint: "先建模" },
      { value: 3, label: "直接打开 AI 聊天窗口", hint: "先聊需求" },
    ],
    note: "场景题，不进入核心四维分数，只作为氛围信号。",
  },
  {
    id: "SCN2",
    prompt: "程序崩溃，报了一个从未见过的错误，你会？",
    category: "scenario",
    input: "choice",
    choices: [
      { value: -3, label: "开 Debugger 追调用栈", hint: "审计流" },
      { value: 0, label: "把报错丢给 AI 看建议", hint: "混合流" },
      { value: 3, label: "重启 IDE/电脑并祈祷", hint: "权限流" },
    ],
    note: "用于彩蛋 `SUDO` 检测。",
  },
  {
    id: "SIG1",
    prompt: "我的代码很少出 Bug，即使我经常快速交付。",
    category: "signal",
    input: "likert",
    direction: "right",
    note: "用于彩蛋 `BUG` 检测，不进入主维度。",
  },
  {
    id: "SIG2",
    prompt: "我完成功能的速度比大量依赖 AI 的朋友还快。",
    category: "signal",
    input: "likert",
    direction: "left",
    note: "用于彩蛋 `LEGEND` 检测，不进入主维度。",
  },
];

export const questionnaireQuestions = questions.filter((question) => question.category === "core");

export const likertLabels = [
  { value: -3, label: "极度不认同" },
  { value: -2, label: "不认同" },
  { value: -1, label: "略不认同" },
  { value: 0, label: "中立" },
  { value: 1, label: "略认同" },
  { value: 2, label: "认同" },
  { value: 3, label: "极度认同" },
] as const;

export const personalityProfiles: Record<string, PersonalityProfile> = {
  MDRC: {
    code: "MDRC",
    chineseName: "数字考古学家",
    englishName: "The Digital Archaeologist",
    summary: "每一行代码都是文物，AI 的污染不可接受。",
    quote: "AI 生成的代码？那是技术债务的种子。",
    hashtags: ["#纯手工代码", "#反AI阵线"],
    vibeLabel: "冷静、克制、极度手工",
    imageName: "MDRC.png",
  },
  MDRP: {
    code: "MDRP",
    chineseName: "代码工匠",
    englishName: "The Code Artisan",
    summary: "慢工出细活，但目标是交付经得起时间考验的产品。",
    quote: "优雅与可靠，是我的底线。",
    hashtags: ["#工程美学", "#质量至上"],
    vibeLabel: "稳健交付派",
    imageName: "MDRP.png",
  },
  MDJC: {
    code: "MDJC",
    chineseName: "直觉原教旨主义者",
    englishName: "The Intuition Purist",
    summary: "凭借深厚内功快速手写，厌恶 AI 的冗余方案。",
    quote: "AI 写的代码太啰嗦，我十行能搞定它五十行。",
    hashtags: ["#反冗余", "#野生高手"],
    vibeLabel: "手写快刀流",
    imageName: "MDJC.png",
  },
  MDJP: {
    code: "MDJP",
    chineseName: "手动快跑者",
    englishName: "The Manual Sprinter",
    summary: "手写速度极快，测试放后面，先冲线。",
    quote: "能跑就行，又不是不能用。",
    hashtags: ["#YOLO手工", "#莽夫流"],
    vibeLabel: "手动疾跑流",
    imageName: "MDJP.png",
  },
  ADRC: {
    code: "ADRC",
    chineseName: "AI 架构师",
    englishName: "The AI Architect",
    summary: "把 AI 当打字员，蓝图、审计和重构都由自己掌控。",
    quote: "我是大脑，AI 是手指。",
    hashtags: ["#AI指挥官", "#架构主导"],
    vibeLabel: "高控制 AI 流",
    imageName: "ADRC.png",
  },
  ADRP: {
    code: "ADRP",
    chineseName: "效率之魔",
    englishName: "The Efficiency Demon",
    summary: "AI 生成，快速审计，追求工业化量产效率。",
    quote: "效率就是一切，AI 让我的想法秒变现实。",
    hashtags: ["#量产代码", "#效率狂魔"],
    vibeLabel: "高效流水线",
    imageName: "ADRP.png",
  },
  ADJC: {
    code: "ADJC",
    chineseName: "上帝视角者",
    englishName: "The God-Viewer",
    summary: "因为懂底层，所以敢完全信任 AI 的高级逻辑。",
    quote: "原理我都懂，AI 只是替我打字。",
    hashtags: ["#信任AI", "#高阶玩家"],
    vibeLabel: "高阶放权派",
    imageName: "ADJC.png",
  },
  ADJP: {
    code: "ADJP",
    chineseName: "实用主义提示词专家",
    englishName: "The Pragmatic Prompter",
    summary: "懂技术，但坚信能跑就行，是最高产的交付型开发者。",
    quote: "代码是手段，产品是目的。",
    hashtags: ["#高产", "#Prompt之神"],
    vibeLabel: "Prompt 生产流",
    imageName: "ADJP.png",
  },
  AVRC: {
    code: "AVRC",
    chineseName: "Vibe 纠错员",
    englishName: "The Vibe Debugger",
    summary: "不懂原理但极其怕 Bug，通过反复测试把 AI 驯服。",
    quote: "我虽然不懂，但我会测。",
    hashtags: ["#焦虑测试", "#AI驯化"],
    vibeLabel: "焦虑修正流",
    imageName: "AVRC.png",
  },
  AVRP: {
    code: "AVRP",
    chineseName: "提示词炼金术师",
    englishName: "The Prompt Alchemist",
    summary: "在 Prompt 循环中寻找真理，用测试集验证 AI。",
    quote: "每次 Prompt 调整都是一次化学实验。",
    hashtags: ["#炼金术", "#测试驱动Vibe"],
    vibeLabel: "提示词实验流",
    imageName: "AVRP.png",
  },
  AVJC: {
    code: "AVJC",
    chineseName: "代码诗人",
    englishName: "The Code Poet",
    summary: "追求 AI 生成代码的美感和氛围，不纠结底层逻辑。",
    quote: "代码要像诗一样，有呼吸感。",
    hashtags: ["#代码美学", "#氛围编程"],
    vibeLabel: "审美导向流",
    imageName: "AVJC.png",
  },
  AVJP: {
    code: "AVJP",
    chineseName: "纯血 Vibe-Coder",
    englishName: "The Pureblood Vibe-Coder",
    summary: "不看代码，只看运行结果。If it vibes, it works。",
    quote: "我不知道什么是 DNS，但我的网站 vibes 对了。",
    hashtags: ["#YOLO", "#VibeCoding", "#赛博顶真"],
    vibeLabel: "纯 Vibe 交付流",
    imageName: "AVJP.png",
  },
  MVRC: {
    code: "MVRC",
    chineseName: "焦虑的初学者",
    englishName: "The Anxious Novice",
    summary: "不敢用 AI 怕出错，自己写也心虚，陷入文档焦虑。",
    quote: "我该信 AI 还是信自己？",
    hashtags: ["#新手焦虑", "#文档地狱"],
    vibeLabel: "焦虑学习流",
    imageName: "MVRC.png",
  },
  MVRP: {
    code: "MVRP",
    chineseName: "战战兢兢的模仿者",
    englishName: "The Trembling Mimic",
    summary: "照着 AI 代码一行行手敲，试图以模仿习得技术。",
    quote: "敲一遍，应该就能记住吧？",
    hashtags: ["#模仿学习", "#笨办法"],
    vibeLabel: "低风险模仿流",
    imageName: "MVRP.png",
  },
  MVJC: {
    code: "MVJC",
    chineseName: "伪装的极简主义者",
    englishName: "The Pseudo-Minimalist",
    summary: "讨厌 AI 但也不太懂底层，维持简单规模与原生偏好。",
    quote: "框架都是噱头，原生最可靠。",
    hashtags: ["#原生至上", "#极简伪装"],
    vibeLabel: "极简保守流",
    imageName: "MVJC.png",
  },
  MVJP: {
    code: "MVJP",
    chineseName: "Vibe 尝试者",
    englishName: "The Vibe Try-Hard",
    summary: "想要 Vibe 但还没掌握 Prompt 技巧，处于痛苦探索期。",
    quote: "为什么 AI 就是不懂我？",
    hashtags: ["#Vibe失败", "#痛苦摸索"],
    vibeLabel: "探索试错流",
    imageName: "MVJP.png",
  },
  SING: {
    code: "SING",
    chineseName: "奇点人",
    englishName: "The Singularity",
    summary: "不再思考代码，直接意识流控制 LLM 构建整个系统。",
    quote: "键盘只是低带宽接口。",
    hashtags: ["#意识流开发", "#人机融合"],
    vibeLabel: "终局融合态",
    imageName: "SING.png",
    isEasterEgg: true,
  },
  BUG: {
    code: "BUG",
    chineseName: "Bug 制造机",
    englishName: "Bug Factory",
    summary: "每次 vibe 成功一次，就会意外放出十个隐藏 Bug。",
    quote: "先上线，Bug 会自己暴露。",
    hashtags: ["#高危交付", "#队友噩梦"],
    vibeLabel: "高风险混沌态",
    imageName: "BUG.png",
    isEasterEgg: true,
  },
  LEGEND: {
    code: "LEGEND",
    chineseName: "传说",
    englishName: "The Legend",
    summary: "以 MDRC 的姿态写代码，却拥有接近 AVJP 的产能。",
    quote: "速度与严谨，不冲突。",
    hashtags: ["#神级开发者", "#双修成功"],
    vibeLabel: "神话级形态",
    imageName: "LGND.png",
    isEasterEgg: true,
  },
  VOID: {
    code: "VOID",
    chineseName: "虚无主义者",
    englishName: "The Void",
    summary: "编程毫无意义，代码只是浪费电，一切都是 0。",
    quote: "提交或不提交，都不会改变宇宙热寂。",
    hashtags: ["#全中立", "#选择困难"],
    vibeLabel: "零点态",
    imageName: "VOID.png",
    isEasterEgg: true,
  },
  HALL: {
    code: "HALL",
    chineseName: "幻想派",
    englishName: "The Delusional",
    summary: "坚信 vibe 对了，不需要懂 DNS 也能让服务器跑起来。",
    quote: "基础设施会感受到我的诚意。",
    hashtags: ["#高氛围", "#低解释性"],
    vibeLabel: "高幻觉态",
    imageName: "HALL.png",
    isEasterEgg: true,
  },
  SUDO: {
    code: "SUDO",
    chineseName: "权限至上者",
    englishName: "The Overlord",
    summary: "所有问题都可以通过 sudo、重启或祈祷解决。",
    quote: "权限够高，现实会让路。",
    hashtags: ["#重启大法", "#权限流"],
    vibeLabel: "特权修复流",
    imageName: "SUDO.png",
    isEasterEgg: true,
  },
};
