name: CI tests

permissions:
  contents: read

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  merge_group:
  workflow_call:

jobs:
  format:
    name: Code Format
    strategy:
      fail-fast: false
      matrix:
        app: [web, miniapp]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: extractions/setup-just@v4
      - uses: oven-sh/setup-bun@v2
      - run: just format-${{ matrix.app }}

  lint:
    name: Code Lint
    strategy:
      fail-fast: false
      matrix:
        app: [web, miniapp]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: extractions/setup-just@v4
      - uses: oven-sh/setup-bun@v2
      - run: just lint-${{ matrix.app }}

  check:
    name: Code Check
    strategy:
      fail-fast: false
      matrix:
        app: [web, miniapp]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: extractions/setup-just@v4
      - uses: oven-sh/setup-bun@v2
      - run: just check-${{ matrix.app }}

  build:
    name: Build Test
    strategy:
      fail-fast: false
      matrix:
        app: [web, miniapp]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: extractions/setup-just@v4
      - uses: oven-sh/setup-bun@v2
      - name: Get font version
        if: matrix.app == 'web'
        id: font-version
        run: |
          just font-version | tee -a "$GITHUB_OUTPUT"
      - uses: actions/cache@v5
        if: matrix.app == 'web'
        with:
          path: .cache/fonts
          key: cache-font-${{ steps.font-version.outputs.wenkai-version }}-${{ steps.font-version.outputs.xihei-version }}
      - run: just build-${{ matrix.app }}
        env:
          # Env vars for web build
          PUBLIC_SITE_URL: https://example.github.io
          PUBLIC_BASE_PATH: /
          # Env vars for miniapp build
          TARO_APP_ID: test-app-id
