name: CI tests

permissions:
  contents: read

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  merge_group:
  workflow_call:

jobs:
  format-web:
    name: Code Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v4
      - uses: oven-sh/setup-bun@v2
      - run: just format-web

  lint-web:
    name: Code Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v4
      - uses: oven-sh/setup-bun@v2
      - run: just lint-web

  check-web:
    name: Code Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v4
      - uses: oven-sh/setup-bun@v2
      - run: just check-web

  build-web:
    name: Build Web App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v4
      - uses: oven-sh/setup-bun@v2
      - name: Get font version
        id: font-version
        run: |
          just font-version | tee -a "$GITHUB_OUTPUT"
      - uses: actions/cache@v5
        with:
          path: .cache/fonts
          key: cache-font-${{ steps.font-version.outputs.wenkai-version }}-${{ steps.font-version.outputs.xihei-version }}
      - run: just build-web
        env:
          PUBLIC_SITE_URL: https://example.github.io
          PUBLIC_BASE_PATH: /

  format-miniapp:
    name: Miniapp CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v4
      - uses: oven-sh/setup-bun@v2
      - run: just format-miniapp

  lint-miniapp:
    name: Miniapp CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v4
      - uses: oven-sh/setup-bun@v2
      - run: just lint-miniapp

  check-miniapp:
    name: Miniapp CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v4
      - uses: oven-sh/setup-bun@v2
      - run: just check-miniapp

  build-miniapp:
    name: Miniapp CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v4
      - uses: oven-sh/setup-bun@v2
      - run: just build-miniapp
        env:
          TARO_APP_ID: test-app-id
