name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write
  id-token: write
  actions: read

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/renovate.json"
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-n-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      PUBLIC_SITE_URL: ${{ format('https://{0}.github.io', github.repository_owner) }}
      PUBLIC_BASE_PATH: ${{ github.event.repository.name == format('{0}.github.io', github.repository_owner) && '/' || format('/{0}/', github.event.repository.name) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Just
        uses: extractions/setup-just@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Get font version
        id: font-version
        run: |
          just font-version | tee -a "$GITHUB_OUTPUT"

      - name: Cache Font
        uses: actions/cache@v6
        with:
          path: .cache/fonts
          key: cache-font-${{ steps.font-version.outputs.wenkai-version }}-${{ steps.font-version.outputs.xihei-version }}

      - name: Build Documentation
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: just build-web

      - name: Configure Pages
        uses: actions/configure-pages@v6

      - name: Upload Files
        uses: actions/upload-pages-artifact@v5
        with:
          path: "apps/web/dist"

      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
